### ISSUE TITLE
EtcdBackupCronJobStatusFailed fires when not needed

### ISSUE THREAD

**Issue by matthias4217** [adfinis/openshift-etcd-backup#40] opened 2022-11-21 12:43 UTC
We use this helm chart on our OKD cluster, and it's been working pretty nicely so far. However, the `EtcdBackupCronJobStatusFailed` has started firing when a job is running.

However, I don't understand why I've started receiving such errors only recently. We've recently updated the cluster, which is probably the cause. But the issue might come from something else.

**Cluster version** : `4.11.0-0.okd-2022-11-05-030711`

## Solutions or workarounds

I've tried to replace `kube_job_status_succeeded{namespace="infra-backup-etcd"} == 0` by `kube_job_status_failed{namespace="infra-backup-etcd"} > 0`, but I'm not sure whether it would raise an alert in case of a failure to schedule a job.

Another solution would be `kube_job_status_succeeded{namespace="infra-backup-etcd"} + kube_job_status_active{namespace="infra-backup-etcd"} != 1`. It seems to work fine, though there could still be some cases I've missed.

**Comment by hairmare** [comment] 2023-01-05 10:04
I don't think we've been able to reproduce this at any point. It might be 4.11 specific, we don't currently have that in production because we stick with LTS versions so it's less tested.

**Comment by tongpu** [comment] 2024-09-05 06:16
Closing because we've not been able to reproduce the issue and didn't receive any further feedback.

**Closed by tongpu** 2024-09-05 06:16 UTC
